COPY INTO PORTFOLIO_DB.RAW.BRANCH
FROM @PORTFOLIO_DB.UTIL.BANKING_STAGE
FILES = ('branch.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB.UTIL.BANKING_CSV_FORMAT'
)
ON_ERROR = ABORT_STATEMENT;


COPY INTO PORTFOLIO_DB.RAW.PRODUCT
FROM @PORTFOLIO_DB.UTIL.BANKING_STAGE
FILES = ('product.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB.UTIL.BANKING_CSV_FORMAT'
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO PORTFOLIO_DB.RAW.CUSTOMER
FROM @PORTFOLIO_DB.UTIL.BANKING_STAGE
FILES = ('customer.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB.UTIL.BANKING_CSV_FORMAT'
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO PORTFOLIO_DB.RAW.ACCOUNT
FROM @PORTFOLIO_DB.UTIL.BANKING_STAGE
FILES = ('account.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB.UTIL.BANKING_CSV_FORMAT'
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO PORTFOLIO_DB.RAW.CUSTOMER_ACCOUNT_RELATIONSHIP
FROM @PORTFOLIO_DB.UTIL.BANKING_STAGE
FILES = ('customer_account_relationship.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB.UTIL.BANKING_CSV_FORMAT'
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO PORTFOLIO_DB.RAW.ACCOUNT_TRANSACTION
FROM @PORTFOLIO_DB.UTIL.BANKING_STAGE
FILES = ('account_transaction.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB.UTIL.BANKING_CSV_FORMAT'
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO PORTFOLIO_DB.RAW.LOAN
FROM @PORTFOLIO_DB.UTIL.BANKING_STAGE
FILES = ('loan.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB.UTIL.BANKING_CSV_FORMAT'
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO PORTFOLIO_DB.RAW.LOAN_PAYMENT
FROM @PORTFOLIO_DB.UTIL.BANKING_STAGE
FILES = ('loan_payment.csv')
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB.UTIL.BANKING_CSV_FORMAT'
)
ON_ERROR = ABORT_STATEMENT;