version: 2

sources:
  - name: raw
    database: PORTFOLIO_DB
    schema: RAW

    tables:
      - name: branch
        identifier: BRANCH

      - name: product
        identifier: PRODUCT

      - name: customer
        identifier: CUSTOMER

      - name: account
        identifier: ACCOUNT

      - name: customer_account_relationship
        identifier: CUSTOMER_ACCOUNT_RELATIONSHIP

      - name: account_transaction
        identifier: ACCOUNT_TRANSACTION

      - name: loan
        identifier: LOAN

      - name: loan_payment
        identifier: LOAN_PAYMENT