USE WAREHOUSE DEV_WH;
USE DATABASE PORTFOLIO_DB;
USE SCHEMA UTIL;

CREATE OR REPLACE FILE FORMAT BANKING_CSV_FORMAT
    TYPE = CSV
    COMPRESSION = AUTO
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('')
    EMPTY_FIELD_AS_NULL = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    DATE_FORMAT = AUTO
    TIMESTAMP_FORMAT = AUTO
    ENCODING = 'UTF8'
    COMMENT = 'CSV format for synthetic banking data';

CREATE OR REPLACE STAGE BANKING_STAGE
    FILE_FORMAT = (
        FORMAT_NAME = 'PORTFOLIO_DB.UTIL.BANKING_CSV_FORMAT'
    )
    COMMENT = 'Internal stage for synthetic banking CSV files';

SHOW FILE FORMATS IN SCHEMA PORTFOLIO_DB.UTIL;
SHOW STAGES IN SCHEMA PORTFOLIO_DB.UTIL;